### ISSUE TITLE
LoRaPacket.h Error

### ISSUE THREAD

**Issue by 1992alexander** [allthingstalk/arduino-lora#2]
Hi,

we have those issues with the following command:
sudo g++ -lpthread -lrt from our application.cpp arduPi.o SX1272.o -o from our application 
<In file included from EmbitLoRaModem.h:11:0, from our application.cpp:5:
LoRaModem.h:10:24: fatal error: LoRaPacket.h: No such file or directory
# include <LoRaPacket.h>

compilation terminated.>

If you have any idears how to solve this problem can you message us?!
Happy programming
Alex

**Comment by jan-bogaerts** [comment]
HI,
Looking at your sudo statement, I believe you are trying to build it on something other then for the sodaq mbili board from our kit?
The library uses   '<>' style of includes for the header files. You might have to put the library in your compiler's library path instead of directly in your project.
